config/routes.rb
Rails.application.routes.draw do
  resources :prescriptions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
end

app/models/patient.rb
class Patient < ApplicationRecord
  include ActiveRecord::PessimisticLocking
  has_many :appointments
  has_many :prescriptions
  has_many :physicians, through: :appointments
end

app/models/physician.rb
class Physician < ApplicationRecord
  has_many :appointments
  has_many :patients, through: :appointments
end

app/models/prescription.rb
class Prescription < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  before_action :set_prescription, only: [:show, :edit, :update, :destroy]

  # GET /prescriptions
  # GET /prescriptions.json
  def index
    @prescriptions = Prescription.all
  end

  # GET /prescriptions/1
  # GET /prescriptions/1.json
  def show
  end

  before_action :acquire_patient_lock, :only => [:new, :create, :edit, :update]

  # acquire/reacquire patient lock
  def acquire_patient_lock

    @patient = Patient.find(params[:patient_id])
    
    unless @patient.acquire_pessimistic_lock(current_user, action_name)
      @prescription ||= Prescription.new(:patient_id => params[:patient_id])
      @prescription.errors[:base] << "Unable to acquire Patient Edit Lock"
      logger.info "Unable to acquire lock for the user #{current_user.name}"
    end
  end
  private :acquire_patient_lock
  
  # GET /prescriptions/new
  def new
    @prescription ||= Prescription.new(:patient_id => params[:patient_id])
  end

  # GET /prescriptions/1/edit
  def edit
  end

  # POST /prescriptions
  # POST /prescriptions.json
  def create
    @prescription = Prescription.new(prescription_params)

    respond_to do |format|
      if @prescription.save
        @patient.release_pessimistic_lock(current_user)
        format.html { redirect_to @prescription, notice: 'Prescription was successfully created.' }
        format.json { render :show, status: :created, location: @prescription }
      else
        format.html { render :new }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prescriptions/1
  # PATCH/PUT /prescriptions/1.json
  def update
    respond_to do |format|
      if @prescription.update(prescription_params)
        format.html { redirect_to @prescription, notice: 'Prescription was successfully updated.' }
        format.json { render :show, status: :ok, location: @prescription }
      else
        format.html { render :edit }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prescriptions/1
  # DELETE /prescriptions/1.json
  def destroy
    @prescription.destroy
    respond_to do |format|
      format.html { redirect_to prescriptions_url, notice: 'Prescription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prescription
      @prescription = Prescription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prescription_params
      params.require(:prescription).permit(:name, :patient_id, :drug, :issued_at)
    end

    private
    def current_user
      # test sets thread variable
      @current_user ||= Thread.current.thread_variable_get(:user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyAwesomeApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/prescriptions/_form.html.erb
<%= form_with(model: prescription, local: true) do |form| %>
  <% if prescription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prescription.errors.count, "error") %> prohibited this prescription from being saved:</h2>

      <ul>
      <% prescription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :prescription_name %>
  </div>

  <div class="field">
    <%= form.label :patient_id %>
    <%= form.number_field :patient_id, id: :prescription_patient_id %>
  </div>

  <div class="field">
    <%= form.label :drug %>
    <%= form.text_field :drug, id: :prescription_drug %>
  </div>

  <div class="field">
    <%= form.label :issued_at %>
    <%= form.date_select :issued_at, id: :prescription_issued_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/prescriptions/edit.html.erb
<h1>Editing Prescription</h1>

<%= render 'form', prescription: @prescription %>

<%= link_to 'Show', @prescription %> |
<%= link_to 'Back', prescriptions_path %>

app/views/prescriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prescriptions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Patient</th>
      <th>Drug</th>
      <th>Issued at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prescriptions.each do |prescription| %>
      <tr>
        <td><%= prescription.name %></td>
        <td><%= prescription.patient_id %></td>
        <td><%= prescription.drug %></td>
        <td><%= prescription.issued_at %></td>
        <td><%= link_to 'Show', prescription %></td>
        <td><%= link_to 'Edit', edit_prescription_path(prescription) %></td>
        <td><%= link_to 'Destroy', prescription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prescription', new_prescription_path %>

app/views/prescriptions/new.html.erb
<h1>New Prescription</h1>

<%= render 'form', prescription: @prescription %>

<%= link_to 'Back', prescriptions_path %>

app/views/prescriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @prescription.name %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @prescription.patient_id %>
</p>

<p>
  <strong>Drug:</strong>
  <%= @prescription.drug %>
</p>

<p>
  <strong>Issued at:</strong>
  <%= @prescription.issued_at %>
</p>

<%= link_to 'Edit', edit_prescription_path(@prescription) %> |
<%= link_to 'Back', prescriptions_path %>